import test from "node:test";
import assert from "node:assert/strict";
import { buildSync } from "esbuild";
function bundle(path){const result=buildSync({entryPoints:[path],bundle:true,platform:"node",format:"cjs",write:false});const module={exports:{}};new Function("module","exports",result.outputFiles[0].text)(module,module.exports);return module.exports}
const {createDemoWorkspace,mastery,masteryStatus,priorities,reconcileEvidence,alignment,makeManualQuestions}=bundle("lib/teacher-data.ts");
const {preparationGaps,responseFlag,studentReview,applyAnswerKey,parseAnswerKey,normalizeRecognizedResponses}=bundle("lib/teacher-workflow.ts");
const {catalogFor,californiaStandards}=bundle("lib/teacher-catalog.ts");
const {hasCuratedLesson,lessonContent}=bundle("lib/teacher-lessons.ts");
function preparedAssignment(){const a=structuredClone(createDemoWorkspace().assessments[0]);a.source="manual";a.answerKeyVerified=true;a.questions=a.questions.slice(0,3).map(q=>({...q,verified:true}));a.responses=[];return a;}

test("student scanning waits for a confirmed key and reviewed standards",()=>{const a=preparedAssignment();assert.equal(preparationGaps(a).ready,true);a.answerKeyVerified=false;assert.equal(preparationGaps(a).ready,false);a.answerKeyVerified=true;a.questions[0].verified=false;assert.equal(preparationGaps(a).ready,false);a.questions[0].verified=true;a.questions[0].answer="";assert.equal(preparationGaps(a).ready,false)});
test("clear-answer approval excludes uncertain, missing, incorrect, and unprepared answers",()=>{const q=preparedAssignment().questions[0];const r={answer:"238",correct:true,confidence:95,verified:false};assert.equal(responseFlag(r,q),null);assert.ok(responseFlag({...r,confidence:89},q));assert.ok(responseFlag({...r,correct:false},q));assert.ok(responseFlag({...r,answer:""},q));assert.ok(responseFlag(r,{...q,verified:false}));});
test("missing or duplicate recognition remains an explicit pending answer",()=>{const a=preparedAssignment();const q=a.questions;const recognized=normalizeRecognizedResponses(a,"s1",[{questionId:q[0].id,answer:q[0].answer,correct:true,misconception:"",confidence:95},{questionId:q[1].id,answer:"A",correct:true,misconception:"",confidence:99},{questionId:q[1].id,answer:"B",correct:true,misconception:"",confidence:99},{questionId:"foreign-question",answer:"1",correct:true,misconception:"",confidence:100}]);assert.equal(recognized.length,3);assert.equal(recognized[0].confidence,95);assert.equal(recognized[1].confidence,0);assert.equal(recognized[2].confidence,0);assert.ok(recognized.every(r=>!r.verified));a.responses=recognized;const review=studentReview(a,"s1");assert.equal(review.clear.length,1);assert.equal(review.flagged.length,2);assert.equal(review.complete,false);assert.equal(review.score,null)});
test("changing the answer key invalidates affected grades and removes stale evidence",()=>{const a=preparedAssignment();a.questions=a.questions.slice(0,1);a.responses=[{id:"r1",studentId:"s1",questionId:a.questions[0].id,answer:a.questions[0].answer,correct:true,misconception:"",confidence:98,verified:true}];const students=[{id:"s1",classId:a.classId,evidence:[]}];const reviewed=reconcileEvidence(students,a);assert.equal(reviewed[0].evidence.length,1);const changed=applyAnswerKey(a,{[a.questions[0].id]:"Corrected teacher key"});assert.equal(changed.answerKeyVerified,false);assert.equal(changed.responses[0].verified,false);assert.equal(changed.responses[0].confidence,0);assert.equal(reconcileEvidence(reviewed,changed)[0].evidence.length,0);assert.equal(studentReview(changed,"s1").complete,false);});
test("numbered answer keys match question numbers and preserve multiline reasoning",()=>{const a=preparedAssignment();const answers=parseAnswerKey("1. 238\nUse partial products.\nQ2: 42,306 < 42,360\n9. Ignore an unknown question",a.questions);assert.equal(answers[a.questions[0].id],"238\nUse partial products.");assert.equal(answers[a.questions[1].id],"42,306 < 42,360");assert.equal(Object.keys(answers).length,2)});
test("assignment alignment measures the teacher’s intended standards",()=>{const a=preparedAssignment();a.questions=a.questions.slice(0,2).map(q=>({...q,alignment:100}));a.targetStandards=[a.questions[0].standard];assert.equal(alignment(a),50);a.questions[1].excluded=true;assert.equal(alignment(a),100)});
test("California catalogs use official records and respect grade, framework, and subject",()=>{const w={customStandards:[{code:"DISTRICT.2",grade:2,framework:"District",subject:"Math"}]};assert.equal(californiaStandards.length,78);assert.equal(catalogFor(w,4,"California","Math").length,34);assert.equal(catalogFor(w,4,"California","ELA").length,44);assert.equal(catalogFor(w,2,"California","Math").length,0);assert.equal(catalogFor(w,2,"District","Math")[0].code,"DISTRICT.2");assert.ok(californiaStandards.every(s=>s.source.startsWith("https://www2.cde.ca.gov/cacs/id/web/")&&s.wording.length>10));assert.equal(new Set(californiaStandards.map(s=>s.code)).size,78);});
test("a new math standard cannot silently receive the old generic ELA lesson",()=>{const s=californiaStandards.find(s=>s.code==="4.NF.1");assert.equal(hasCuratedLesson(s),false);assert.throws(()=>lessonContent(s),/specific reteach lesson/);assert.equal(hasCuratedLesson(californiaStandards.find(s=>s.code==="4.NBT.B.5")),true)});
test("the sample has 24 fictional students and all answers refer to an existing question and student",()=>{const w=createDemoWorkspace();assert.equal(w.students.length,24);assert.equal(new Set(w.students.map(s=>s.id)).size,24);for(const a of w.assessments){assert.equal(a.responses.length,w.students.length*a.questions.length);for(const r of a.responses){assert.ok(a.questions.some(q=>q.id===r.questionId));assert.ok(w.students.some(s=>s.id===r.studentId));}assert.ok(alignment(a)>=0&&alignment(a)<=100)}});
test("mastery uses the three latest observations and cannot be declared from one high score",()=>{const s={id:"learner",evidence:[{standard:"A",score:100,date:"2026-01-01"},{standard:"A",score:70,date:"2026-01-02"},{standard:"A",score:80,date:"2026-01-03"},{standard:"A",score:90,date:"2026-01-04"},{standard:"B",score:100,date:"2026-01-04"}]};assert.equal(mastery(s,"A"),80);assert.equal(masteryStatus(s,"A"),"Mastered");assert.equal(masteryStatus(s,"B"),"Building evidence");assert.equal(mastery(s,"C"),null);assert.equal(masteryStatus(s,"C"),"No evidence")});
test("unreviewed and excluded questions never affect mastery; correcting an answer replaces evidence",()=>{const s={id:"student",classId:"class",evidence:[]},other={id:"other",classId:"different",evidence:[]};const a={id:"assessment",classId:"class",title:"Review check",questions:[{id:"q1",standard:"A",verified:true,excluded:false},{id:"q2",standard:"B",verified:false,excluded:false},{id:"q3",standard:"C",verified:true,excluded:true}],responses:[{id:"r1",studentId:"student",questionId:"q1",correct:false,verified:true},{id:"r2",studentId:"student",questionId:"q2",correct:true,verified:true},{id:"r3",studentId:"student",questionId:"q3",correct:true,verified:true}]};const once=reconcileEvidence([s,other],a);assert.equal(once[0].evidence.length,1);assert.equal(once[0].evidence[0].score,0);assert.equal(once[1].evidence.length,0);a.responses[0].correct=true;const twice=reconcileEvidence(once,a);assert.equal(twice[0].evidence.length,1);assert.equal(twice[0].evidence[0].score,100);a.responses[0].verified=false;assert.equal(reconcileEvidence(twice,a)[0].evidence.length,0)});
test("priorities identify the documented twelve-student word-problem group",()=>{const w=createDemoWorkspace();const list=priorities(w.students);assert.equal(list[0].standard.code,"4.OA.A.3");assert.equal(list[0].students.length,12);assert.equal(list[0].tier,"Whole class");assert.ok(list.every((p,i)=>i===0||list[i-1].score>=p.score))});
test("manually entered questions stay unclassified until teacher review",()=>{const qs=makeManualQuestions("1. Solve 34 × 7.\n\n2. Explain the operation plan.");assert.equal(qs.length,2);assert.ok(qs.every(q=>!q.verified&&q.standard===""&&q.confidence===0));assert.equal(qs[0].text,"Solve 34 × 7.")});
