import test from "node:test";
import assert from "node:assert/strict";
import { buildSync } from "esbuild";
function bundle(path){const result=buildSync({entryPoints:[path],bundle:true,platform:"node",format:"cjs",write:false});const module={exports:{}};new Function("module","exports",result.outputFiles[0].text)(module,module.exports);return module.exports}
const {createDemoWorkspace,mastery,masteryStatus,priorities,reconcileEvidence,alignment,makeManualQuestions}=bundle("lib/teacher-data.ts");
test("the sample has 24 fictional students and all answers refer to an existing question and student",()=>{const w=createDemoWorkspace();assert.equal(w.students.length,24);assert.equal(new Set(w.students.map(s=>s.id)).size,24);for(const a of w.assessments){assert.equal(a.responses.length,w.students.length*a.questions.length);for(const r of a.responses){assert.ok(a.questions.some(q=>q.id===r.questionId));assert.ok(w.students.some(s=>s.id===r.studentId));}assert.ok(alignment(a)>=0&&alignment(a)<=100)}});
test("mastery uses the three latest observations and cannot be declared from one high score",()=>{const s={id:"learner",evidence:[{standard:"A",score:100,date:"2026-01-01"},{standard:"A",score:70,date:"2026-01-02"},{standard:"A",score:80,date:"2026-01-03"},{standard:"A",score:90,date:"2026-01-04"},{standard:"B",score:100,date:"2026-01-04"}]};assert.equal(mastery(s,"A"),80);assert.equal(masteryStatus(s,"A"),"Mastered");assert.equal(masteryStatus(s,"B"),"Building evidence");assert.equal(mastery(s,"C"),null);assert.equal(masteryStatus(s,"C"),"No evidence")});
test("unreviewed and excluded questions never affect mastery; correcting an answer replaces evidence",()=>{const s={id:"student",classId:"class",evidence:[]},other={id:"other",classId:"different",evidence:[]};const a={id:"assessment",classId:"class",title:"Review check",questions:[{id:"q1",standard:"A",verified:true,excluded:false},{id:"q2",standard:"B",verified:false,excluded:false},{id:"q3",standard:"C",verified:true,excluded:true}],responses:[{id:"r1",studentId:"student",questionId:"q1",correct:false,verified:true},{id:"r2",studentId:"student",questionId:"q2",correct:true,verified:true},{id:"r3",studentId:"student",questionId:"q3",correct:true,verified:true}]};const once=reconcileEvidence([s,other],a);assert.equal(once[0].evidence.length,1);assert.equal(once[0].evidence[0].score,0);assert.equal(once[1].evidence.length,0);a.responses[0].correct=true;const twice=reconcileEvidence(once,a);assert.equal(twice[0].evidence.length,1);assert.equal(twice[0].evidence[0].score,100);a.responses[0].verified=false;assert.equal(reconcileEvidence(twice,a)[0].evidence.length,0)});
test("priorities identify the documented twelve-student word-problem group",()=>{const w=createDemoWorkspace();const list=priorities(w.students);assert.equal(list[0].standard.code,"4.OA.A.3");assert.equal(list[0].students.length,12);assert.equal(list[0].tier,"Whole class");assert.ok(list.every((p,i)=>i===0||list[i-1].score>=p.score))});
test("manually entered questions stay unclassified until teacher review",()=>{const qs=makeManualQuestions("1. Solve 34 × 7.\n\n2. Explain the operation plan.");assert.equal(qs.length,2);assert.ok(qs.every(q=>!q.verified&&q.standard===""&&q.confidence===0));assert.equal(qs[0].text,"Solve 34 × 7.")});
