"use client";
import {ArrowRight,ArrowUpRight,Sparkles,Users,Target,Files,TrendingUp,Clock,Plus,Lightbulb,CalendarDays,Check,ScanLine,BookOpen} from "lucide-react";
import {useTeacher} from "./teacher-context";
import {PageTitle,SectionTitle,Action,Pill,AvatarStack,Meter,Score,Ring,Insight,TextLink,EmptyState} from "./teacher-shared";
import {priorities,classMastery,masteryStatus,alignment} from "@/lib/teacher-data";
export default function HomeView(){
const {w,classroom,students,assessments,catalog,go}=useTeacher();const ranked=priorities(students,catalog),first=ranked[0],plans=w.lessons.filter(l=>l.classId===classroom.id&&!l.completed);
const avg=catalog.length?Math.round(catalog.reduce((sum,s)=>sum+classMastery(students,s.code),0)/catalog.length):0;
const reviewed=assessments.reduce((sum,a)=>sum+a.questions.filter(q=>q.verified).length,0),enrichment=students.filter(s=>catalog.length>0&&catalog.every(c=>masteryStatus(s,c.code)==="Mastered"));
const dates=[...new Set(students.flatMap(s=>s.evidence.map(e=>e.date)))].sort().slice(-4),values=dates.map(date=>{const es=students.flatMap(s=>s.evidence.filter(e=>e.date===date));return es.length?Math.round(es.reduce((sum,e)=>sum+e.score,0)/es.length):0});
return <><PageTitle eyebrow="A CLEARER PICTURE. A CONFIDENT NEXT STEP." title="Teach tomorrow" description={w.settings.teacherName?"You’ve got this, "+w.settings.teacherName.split(" ")[0]+". Here’s where to focus next.":"You bring the heart. Let’s find your next best teaching move."}><Action onClick={()=>go("/scan")}><ScanLine size={18}/>Scan assignment</Action></PageTitle>
<div className="dashboard-feature-grid"><section className="next-move-card"><div className="feature-topline"><span><Sparkles size={16}/>YOUR NEXT BEST MOVE</span><Pill>{first?"Priority 01":"Start here"}</Pill></div><div className="next-move-body"><div className="next-move-copy"><h2>{first?first.standard.title:"A little insight changes everything."}</h2><p>{first?first.standard.misconception:"Bring in an assignment to discover what it measures and where your students need support."}</p>{first&&<div className="student-preview"><AvatarStack students={first.students}/><span><strong>{first.students.length} of {students.length}</strong> students need support</span></div>}</div>{first?<Ring value={first.mastery} label="class mastery"/>:<div className="empty-feature-icon"><ScanLine size={70} strokeWidth={1}/></div>}</div><div className="feature-bottom"><button className="feature-button" onClick={()=>go(first?"/reteach?standard="+first.standard.code:"/scan")}>{first?"Build this lesson":"Scan your first assignment"}<ArrowUpRight size={18}/></button><span>{first?<><Clock size={15}/>15-minute small group</>:<><ShieldIcon/>You’re always in control</>}</span></div></section>
<section className="plan-preview panel"><div className="section-heading"><h2><CalendarDays size={19}/>On your teaching plan</h2><Pill>{plans.length} saved</Pill></div>{plans.length?<div className="compact-plans">{plans.slice(0,3).map((p,i)=><button key={p.id} className="compact-plan" onClick={()=>go("/reteach?lesson="+p.id)}><span className={"plan-number c"+i}>{String(i+1).padStart(2,"0")}</span><div><strong>{p.title}</strong><span>{p.duration} min · {p.modality}</span></div><ArrowUpRight size={16}/></button>)}</div>:<div className="compact-plans">{ranked.slice(0,3).map((p,i)=><button key={p.standard.code} className="compact-plan" onClick={()=>go("/reteach?standard="+p.standard.code)}><span className={"plan-number c"+i}>{String(i+1).padStart(2,"0")}</span><div><strong>{p.standard.title}</strong><span>{p.tier} · {p.students.length} students</span></div><Plus size={16}/></button>)}{!ranked.length&&<p className="quiet-empty">Your lessons will live here. Start with an assessment or explore the reteach studio.</p>}</div>}<button className="plan-footer" onClick={()=>go("/reteach")}>{plans.length?"Open your lesson plan":"Shape your teaching plan"}<ArrowRight size={16}/></button></section></div>
<div className="stats-ribbon">{[{icon:Users,label:"Students in your class",value:students.length,sub:classroom.demo?"24 different ways to shine":"Your classroom roster"},{icon:Target,label:"Standards in focus",value:catalog.filter(c=>students.some(s=>s.evidence.some(e=>e.standard===c.code))).length,sub:"Connected to real skills"},{icon:Files,label:"Questions reviewed",value:reviewed,sub:assessments.length+" assessments in your workspace"},{icon:TrendingUp,label:"Class understanding",value:avg+"%",sub:"Average of recent evidence"}].map((s,i)=><div className="stat-item" key={s.label}><span className={"stat-icon c"+i}><s.icon size={20}/></span><div><span className="stat-label">{s.label}</span><strong>{s.value}</strong><span className="stat-sub">{s.sub}</span></div></div>)}</div>
<div className="dashboard-middle"><section className="panel priority-panel"><SectionTitle title="A little focus goes a long way" description="Start with the skills that will make the biggest difference."><TextLink onClick={()=>go("/diagnostics")}>All insights</TextLink></SectionTitle>{ranked.length?<div className="priority-list">{ranked.slice(0,3).map((p,i)=><button className="priority-row" key={p.standard.code} onClick={()=>go("/diagnostics?standard="+p.standard.code)}><span className={"priority-num c"+i}>{String(i+1).padStart(2,"0")}</span><div className="priority-name"><h3>{p.standard.title}</h3><div><span>{p.standard.code}</span><span className="separator-dot">·</span><span>{p.students.length} students need a little support</span></div></div><div className="priority-meter"><span>{p.mastery}% class mastery</span><Meter value={p.mastery} tone={i===0?"orange":i===1?"purple":"green"}/></div><ArrowUpRight size={19}/></button>)}</div>:<EmptyState title="Room for new insights" description="Record assessment evidence to see which skills need attention."/>}<Insight>Look beyond the score. A missed word problem can reveal a reading gap, an operation choice, or a calculation error.</Insight></section>
<section className="panel momentum-panel"><SectionTitle title="Little wins add up" description="Your classroom’s learning momentum"/>{values.length>1?<><div className="momentum-total"><strong>{values.at(-1)}<span>%</span></strong><Pill tone="green"><TrendingUp size={13}/>{values.at(-1)!-values[0]} pts</Pill></div><div className="momentum-chart" role="img" aria-label={"Average evidence scores: "+values.join(", ")+" percent"}><svg viewBox="0 0 380 130" preserveAspectRatio="none"><defs><linearGradient id="momentum-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#82b4a3" stopOpacity=".3"/><stop offset="100%" stopColor="#82b4a3" stopOpacity="0"/></linearGradient></defs>{[25,60,95].map(y=><line key={y} x1="0" y1={y} x2="380" y2={y} stroke="#e9eeeb" strokeDasharray="4 5"/>)}<path d={"M "+values.map((v,i)=>i*360/(values.length-1)+10+","+(120-v)).join(" L ")+" L 370,130 L 10,130 Z"} fill="url(#momentum-fill)"/><path className="chart-line" d={"M "+values.map((v,i)=>i*360/(values.length-1)+10+","+(120-v)).join(" L ")} fill="none" stroke="#477d68" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>{values.map((v,i)=><circle key={i} cx={i*360/(values.length-1)+10} cy={120-v} r="4" fill="#477d68" stroke="white" strokeWidth="2"/>)}</svg><div className="chart-labels">{dates.map(d=><span key={d}>{new Date(d+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span>)}</div></div><p className="field-help">Every check-in is a new piece of the picture.</p></>:<div className="quiet-empty">Add more than one dated check-in to see progress over time.</div>}</section></div>
<div className="dashboard-bottom"><section className="panel assessment-recent"><SectionTitle title="Fresh from your classroom"><TextLink onClick={()=>go("/assessments")}>View all</TextLink></SectionTitle>{assessments.slice(0,2).map(a=><button className="recent-assessment" key={a.id} onClick={()=>go("/assessments?id="+a.id)}><span className={"document-icon "+(a.subject==="ELA"?"purple":"")}><Files size={24}/></span><div><h3>{a.title}</h3><span>{a.subject} · {a.questions.length} questions · Grade {a.grade}</span></div><Pill tone={a.status==="Ready"?"green":"amber"}>{a.status}</Pill><ArrowUpRight size={17}/></button>)}{!assessments.length&&<TextLink onClick={()=>go("/scan")}>Add your first assessment</TextLink>}</section><section className="enrichment-card"><div className="enrichment-symbol"><Lightbulb size={27}/></div><div><span className="eyebrow">READY FOR A LITTLE MORE</span><h2>{enrichment.length?enrichment.length+" curious minds.":"Keep curiosity growing."}<br/>A new challenge.</h2><p>{enrichment.length?"These students show mastery across your current standards.":"Make room for deeper thinking with open-ended enrichment tasks."}</p><TextLink onClick={()=>go("/resources?category=Enrichment")}>Find their next challenge</TextLink></div></section></div></>
}
function ShieldIcon(){return <Check size={15}/>}
