"use client";
import {useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import {toast} from "sonner";
import {ArrowLeft,ArrowRight,ArrowUpRight,Plus,Upload,Camera,FileText,Check,CheckCheck,ScanLine,Lightbulb,LoaderCircle,X,Search,Download,Eye,AlertCircle,Target,Users,Pencil,Trash2} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Slider} from "@/components/ui/slider";
import {Checkbox} from "@/components/ui/checkbox";
import {useTeacher} from "./teacher-context";
import {Action,PageTitle,SectionTitle,Pick,Pill,Score,Meter,Ring,EmptyState,Modal,Insight,downloadText,TextLink} from "./teacher-shared";
import {catalogFor} from "@/lib/teacher-catalog";
import {assignmentNextStep,preparationGaps,applyAnswerKey} from "@/lib/teacher-workflow";
import {StudentResponseReview} from "./teacher-review";
import {AnswerKeyReview} from "./teacher-answer-key";
import {alignment,makeManualQuestions,reconcileEvidence} from "@/lib/teacher-data";
import type {Assessment,Question,StudentResponse,Subject} from "@/lib/teacher-types";

export function AssessmentView(){
const {w,assessments,students,save,busy,go}=useTeacher();const params=useSearchParams();const [selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(""),[subject,setSubject]=useState("All subjects"),[tab,setTab]=useState("questions"),[edit,setEdit]=useState<Question|null>(null),[responseEdit,setResponseEdit]=useState<StudentResponse|null>(null),[studentFilter,setStudentFilter]=useState("all"),[newText,setNewText]=useState(""),[adding,setAdding]=useState(false);
useEffect(()=>{setSelected(params.get("id"));setTab(params.get("tab")||"questions")},[params]);
const a=assessments.find(x=>x.id===selected);
const catalog=a?catalogFor(w,a.grade,a.framework):[];
const clearQuestions=a?.questions.filter(q=>!q.verified&&!q.excluded&&q.standard&&q.skill&&q.confidence>=90&&q.alignment>=80&&q.level==="On grade"&&a.targetStandards.includes(q.standard))||[];
async function saveAssessment(next:Assessment,message:string){return save({...w,assessments:w.assessments.map(x=>x.id===next.id?next:x),students:reconcileEvidence(w.students,next)},message)}
function exportAssessment(){if(!a)return;downloadText(a.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")+".csv","Question,Text,Standard,Skill,DOK,Alignment,Confidence,Grade level,Verified\n"+a.questions.map(q=>[q.number,q.text,q.standard,q.skill,q.dok,q.alignment,q.confidence,q.level,q.verified].map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(",")).join("\n"),"text/csv")}
async function verifyQuestion(){if(!a||!edit)return;if(!edit.excluded&&(!edit.standard||!edit.skill.trim())){toast.error("Choose a standard and name the skill before accepting.");return}const questions=a.questions.map(q=>q.id===edit.id?{...edit,verified:true}:q);const previous=a.questions.find(q=>q.id===edit.id)!;const contentChanged=previous.answer!==edit.answer||previous.text!==edit.text||previous.passage!==edit.passage;const next={...a,questions,...(contentChanged?{answerKeyVerified:false,responses:a.responses.map(r=>r.questionId===edit.id?{...r,verified:false,confidence:0}:r)}:{}),status:questions.every(q=>q.verified||q.excluded)?"Ready" as const:"Needs review" as const};if(await saveAssessment(next,"Your standards decision is saved"))setEdit(null)}
async function saveResponse(){if(!a||!responseEdit)return;if(responseEdit.correct&&!responseEdit.answer.trim()){toast.error("Enter the student’s answer before marking it correct.");return;}if(!preparationGaps(a).ready){toast.error("Confirm the assignment standards and answer key first.");return;}const r={...responseEdit,verified:true,confidence:100};const responses=[...a.responses.filter(x=>!(x.studentId===r.studentId&&x.questionId===r.questionId)&&x.id!==r.id),r];const next={...a,responses};if(await save({...w,assessments:w.assessments.map(x=>x.id===a.id?next:x),students:reconcileEvidence(w.students,next)},"Response confirmed"))setResponseEdit(null)}
const filtered=assessments.filter(x=>(subject==="All subjects"||x.subject===subject)&&x.title.toLowerCase().includes(query.toLowerCase()));
return <>{!a?<><PageTitle eyebrow="EVERY QUESTION TELLS A STORY" title="Assignments" description="Keep the assignment, answer key, and student work together."><Action onClick={()=>go("/scan")}><Plus size={17}/>New assignment</Action></PageTitle><div className="filter-bar"><label className="search-box"><Search size={17}/><input aria-label="Search assessments" placeholder="Find an assessment…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Pick label="Filter subject" value={subject} onChange={setSubject} options={["All subjects","Math","ELA","Mixed"]}/><span className="result-count">{filtered.length} assessments</span></div><div className="panel assignment-directory">{filtered.map(item=>{const prep=preparationGaps(item),next=assignmentNextStep(item);return <button className="assignment-list-row" key={item.id} onClick={()=>go(next.href)}><span className="document-icon"><FileText size={22}/></span><div className="assignment-row-copy"><h2>{item.title}</h2><p>{item.subject} · Grade {item.grade} · {item.questions.length} questions · {item.framework}</p></div><div className="assignment-row-next"><Pill tone={prep.ready?"green":"amber"}>{prep.ready?"Ready for student work":"Needs setup"}</Pill><span>{next.label}<ArrowRight size={16}/></span></div></button>})}{!filtered.length&&<EmptyState title={query?"No matching assignments":"Add your first assignment"} description="Upload an assignment or paste questions to begin."><Action onClick={()=>go("/scan")}>New assignment<ArrowRight size={16}/></Action></EmptyState>}</div></>:<>
<button className="back-link" onClick={()=>go("/assessments")}><ArrowLeft size={16}/>All assignments</button><PageTitle eyebrow={a.subject.toUpperCase()+" · GRADE "+a.grade+" · "+a.framework.toUpperCase()} title={a.title} description={a.source==="sample"?"An illustrative assessment with fictional student responses.":a.source==="ai"?"AI suggestions are ready for your professional review.":"Review the questions, then connect them to your standards."}><Action variant="secondary" onClick={exportAssessment}><Download size={16}/>Export report</Action><Action onClick={()=>go("/scan?mode=responses&assessment="+a.id)} disabled={!preparationGaps(a).ready}><Plus size={16}/>Add student work</Action></PageTitle>
<div className="assignment-status-bar"><div><span>Standards alignment</span><strong>{a.questions.length?alignment(a)+"%":"—"}</strong></div><div><span>Questions to review</span><strong>{a.questions.filter(q=>!q.verified&&!q.excluded).length}</strong></div><div><span>Answer key</span><strong>{preparationGaps(a).keyConfirmed?"Confirmed":"Check key"}</strong></div><div><span>Student work</span><strong>{new Set(a.responses.map(r=>r.studentId)).size} added</strong></div></div>
{(a.assignmentUploadIds||a.uploadIds).length>0&&<div className="source-documents"><span>Source documents</span>{(a.assignmentUploadIds||a.uploadIds).map((id,i)=><a key={id} href={"/api/uploads/"+id} target="_blank" rel="noreferrer"><FileText size={14}/>Document {i+1}<ArrowUpRight size={13}/></a>)}</div>}
<Tabs value={tab} onValueChange={setTab}><TabsList className="page-tabs"><TabsTrigger value="questions">1. Assignment review</TabsTrigger><TabsTrigger value="key">2. Answer key</TabsTrigger><TabsTrigger value="responses">3. Student work</TabsTrigger><TabsTrigger value="coverage">Standards report</TabsTrigger></TabsList>
<TabsContent value="questions">{!a.targetStandards.length&&<div className="review-notice"><Target size={18}/><p>Choose the intended standards to measure this assignment’s alignment.</p><button className="text-link" onClick={()=>setTab("coverage")}>Choose standards<ArrowRight size={16}/></button></div>}<div className="panel report-table"><SectionTitle title="Check what each question measures" description="Confirm the suggestions that fit. Open a question to adjust its standard or reasoning."><div className="review-heading-actions">{clearQuestions.length>0&&<Action variant="secondary small" disabled={busy} onClick={()=>{const ids=new Set(clearQuestions.map(q=>q.id));const questions=a.questions.map(q=>ids.has(q.id)?{...q,verified:true}:q);saveAssessment({...a,questions,status:questions.every(q=>q.verified||q.excluded)?"Ready":"Needs review"},clearQuestions.length+" aligned questions confirmed")}}><CheckCheck size={16}/>Confirm {clearQuestions.length} clear matches</Action>}<Action variant="secondary small" onClick={()=>setAdding(true)}><Plus size={15}/>Add questions</Action></div></SectionTitle>{a.questions.length?<Table><TableHeader><TableRow><TableHead>Question</TableHead><TableHead>Skill & standard</TableHead><TableHead>Depth</TableHead><TableHead>Alignment</TableHead><TableHead>Review</TableHead><TableHead/></TableRow></TableHeader><TableBody>{a.questions.map(q=><TableRow className={q.excluded?"excluded":""} key={q.id}><TableCell><button className="question-cell" onClick={()=>setEdit({...q})}><span className="question-number">{String(q.number).padStart(2,"0")}</span><span>{q.text}</span></button></TableCell><TableCell><strong className="cell-title">{q.skill||"Choose a skill"}</strong><span className="cell-meta">{q.standard||"Not assigned"}</span></TableCell><TableCell><Pill>DOK {q.dok}</Pill></TableCell><TableCell><Score value={q.alignment}/><span className="cell-meta">{q.level}</span></TableCell><TableCell>{q.excluded?<Pill>Excluded</Pill>:q.verified?<Pill tone="green"><Check size={12}/>Reviewed</Pill>:<Pill tone="amber">Needs review</Pill>}</TableCell><TableCell><button className="icon-button" aria-label={"Review question "+q.number} onClick={()=>setEdit({...q})}><ArrowUpRight size={18}/></button></TableCell></TableRow>)}</TableBody></Table>:<EmptyState title="Add questions to start reviewing" description="Your document is saved. Paste questions manually while AI scanning is disconnected."><Action onClick={()=>setAdding(true)}>Add questions</Action></EmptyState>}</div></TabsContent>
<TabsContent value="coverage"><div className="coverage-layout"><section className="panel"><SectionTitle title="The full standards picture" description="Coverage is compared with this assessment’s intended standards."/>{catalog.map(s=>{const count=a.questions.filter(q=>!q.excluded&&(q.standard===s.code||q.secondary===s.code)).length;const target=a.targetStandards.includes(s.code);return <div className="coverage-row" key={s.code}><Checkbox aria-label={"Include "+s.code+" as intended standard"} checked={target} onCheckedChange={v=>saveAssessment({...a,targetStandards:v?[...a.targetStandards,s.code]:a.targetStandards.filter(c=>c!==s.code)},"Intended standards updated")}/><div><strong>{s.title}</strong><span>{s.code}</span></div><Meter value={Math.min(100,count/Math.max(1,a.questions.length)*100)} tone={count?"green":"orange"}/><span>{count} questions</span><Pill tone={!count&&target?"amber":count>=3?"green":"neutral"}>{!target?"Optional":!count?"Missing":count===1?"Limited":count>=5?"Heavy":"Covered"}</Pill></div>})}{!catalog.length&&<EmptyState title="Add your standards" description="Create standards for this grade and framework to compare coverage."><Action onClick={()=>go("/standards")}>Open standards library</Action></EmptyState>}</section><section className="panel"><SectionTitle title="Cognitive demand" description="Content coverage and depth are different questions."/>{[1,2,3,4].map((d,i)=>{const count=a.questions.filter(q=>!q.excluded&&q.dok===d).length;return <div className="dok-row" key={d}><div><strong>DOK {d}</strong><span>{["Recall","Skill & concept","Strategic thinking","Extended reasoning"][i]}</span></div><Meter value={count/Math.max(1,a.questions.filter(q=>!q.excluded).length)*100} tone={i===0?"orange":"green"}/><span>{count}</span></div>})}<Insight>Use a model-and-explain task or an error-analysis question when a standard calls for reasoning.</Insight></section></div></TabsContent>
<TabsContent value="key"><AnswerKeyReview assessment={a} onSave={saveAssessment}/></TabsContent><TabsContent value="responses"><StudentResponseReview assessment={a} onEdit={setResponseEdit} onSave={saveAssessment}/></TabsContent></Tabs></>}
<Sheet open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><SheetContent className="review-sheet"><SheetHeader><SheetTitle>Question {edit?.number} · Review alignment</SheetTitle><SheetDescription>Check the question, its expected answer, and the standard it measures.</SheetDescription></SheetHeader>{edit&&<div className="sheet-scroll form-stack">{edit.passage&&<div className="passage"><span>ASSOCIATED PASSAGE</span><p>{edit.passage}</p></div>}<label>Question<textarea value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><details className="review-advanced"><summary>Reading passage & further detail</summary><label>Associated passage (optional)<textarea value={edit.passage} onChange={e=>setEdit({...edit,passage:e.target.value})} placeholder="Keep the passage connected to this question."/></label></details><label>Answer key<textarea value={edit.answer} onChange={e=>setEdit({...edit,answer:e.target.value})}/></label><div className="suggestion-reason"><span><Lightbulb size={16}/>{a?.source==="ai"?"AI suggestion":a?.source==="sample"?"Illustrative analysis":"Teacher analysis"} · {edit.confidence}% confidence</span><p>{edit.reasoning}</p></div><label>Primary standard<Pick label="Primary standard" value={edit.standard} onChange={standard=>setEdit({...edit,standard})} options={[{value:"",label:"Choose a standard"},...catalog.map(s=>({value:s.code,label:s.code+" · "+s.title}))]}/></label><label>Skill being assessed<input value={edit.skill} onChange={e=>setEdit({...edit,skill:e.target.value})} placeholder="e.g. Multiply using partial products"/></label><details className="review-advanced"><summary>Secondary standard, depth & alignment</summary><label>Secondary standard<Pick label="Secondary standard" value={edit.secondary} onChange={secondary=>setEdit({...edit,secondary})} options={[{value:"",label:"None"},...catalog.map(s=>({value:s.code,label:s.code+" · "+s.title}))]}/></label><div className="form-grid"><label>Cognitive demand<Pick label="DOK" value={String(edit.dok)} onChange={dok=>setEdit({...edit,dok:Number(dok)})} options={["1","2","3","4"]}/></label><label>Instructional level<Pick label="Instructional level" value={edit.level} onChange={level=>setEdit({...edit,level:level as Question["level"]})} options={["On grade","Below grade","Above grade","Unrelated"]}/></label></div><label>Alignment · {edit.alignment}%<Slider aria-label="Alignment score" min={0} max={100} step={1} value={[edit.alignment]} onValueChange={v=>setEdit({...edit,alignment:v[0]})}/></label><label>Reason for your decision<textarea value={edit.reasoning} onChange={e=>setEdit({...edit,reasoning:e.target.value})}/></label></details><label className="checkbox-label"><Checkbox checked={edit.excluded} onCheckedChange={v=>setEdit({...edit,excluded:!!v})}/>Mark not applicable / exclude from report</label><Action disabled={busy} onClick={verifyQuestion}><Check size={16}/>Accept & save decision</Action></div>}</SheetContent></Sheet>
<Modal open={adding} onClose={()=>setAdding(false)} title="Add questions" description="Separate each question with a blank line."><div className="form-stack"><label>Questions<textarea className="question-paste" value={newText} onChange={e=>setNewText(e.target.value)}/></label><Action disabled={!newText.trim()||busy} onClick={async()=>{if(!a)return;const qs=makeManualQuestions(newText).map((q,i)=>({...q,number:a.questions.length+i+1}));if(await saveAssessment({...a,questions:[...a.questions,...qs],status:"Needs review"},"Questions added")){setAdding(false);setNewText("")}}}>Add for review<ArrowRight size={16}/></Action></div></Modal>
<Modal open={!!responseEdit} onClose={()=>setResponseEdit(null)} title="Check & confirm this answer" description="Compare the student’s work with the answer key, then confirm your decision."><div className="form-stack">{responseEdit&&a&&<><label>Student<Pick label="Student" value={responseEdit.studentId} onChange={studentId=>{const existing=a.responses.find(r=>r.studentId===studentId&&r.questionId===responseEdit.questionId);setResponseEdit(existing?{...existing}:{...responseEdit,studentId,id:crypto.randomUUID(),answer:"",correct:false,misconception:"",verified:false})}} options={students.map(s=>({value:s.id,label:s.name}))}/></label><label>Question<Pick label="Question" value={responseEdit.questionId} onChange={questionId=>{const existing=a.responses.find(r=>r.studentId===responseEdit.studentId&&r.questionId===questionId);setResponseEdit(existing?{...existing}:{...responseEdit,questionId,id:crypto.randomUUID(),answer:"",correct:false,misconception:"",verified:false})}} options={a.questions.filter(q=>!q.excluded).map(q=>({value:q.id,label:"Q"+q.number+" · "+q.text.slice(0,55)}))}/></label><div className="passage"><p>{a.questions.find(q=>q.id===responseEdit.questionId)?.text}</p><strong>Answer key: {a.questions.find(q=>q.id===responseEdit.questionId)?.answer||"Not recorded"}</strong></div><label>Student’s response<textarea value={responseEdit.answer} onChange={e=>setResponseEdit({...responseEdit,answer:e.target.value})}/></label><label className="checkbox-label"><Checkbox checked={responseEdit.correct} onCheckedChange={v=>setResponseEdit({...responseEdit,correct:!!v})}/>Response is correct</label><label>Likely misconception or observation<textarea value={responseEdit.misconception} onChange={e=>setResponseEdit({...responseEdit,misconception:e.target.value})} placeholder="Record what you observed. Avoid diagnosing from one answer."/></label><Action disabled={busy} onClick={saveResponse}><Check size={16}/>Confirm this answer</Action></>}</div></Modal></>
}
