"use client";
import type {ReactNode} from "react";
import {ArrowUpRight,ArrowRight,Lightbulb,FileText} from "lucide-react";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Progress} from "@/components/ui/progress";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from "@/components/ui/empty";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import type {Student} from "@/lib/teacher-types";
export function Pick({value,onChange,options,label,className=""}:{value:string;onChange:(value:string)=>void;options:(string|{value:string;label:string})[];label:string;className?:string}){return <Select value={value||"__none"} onValueChange={v=>onChange(v==="__none"?"":v)}><SelectTrigger aria-label={label} className={"pick "+className}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==="string"?o:o.value;return <SelectItem key={v} value={v||"__none"}>{typeof o==="string"?o:o.label}</SelectItem>})}</SelectContent></Select>}
export function Pill({children,tone="neutral"}:{children:ReactNode;tone?:string}){return <span className={"pill "+tone}>{children}</span>}
export function Action({children,onClick,variant="",disabled=false,className="",type="button"}:{children:ReactNode;onClick?:()=>void;variant?:string;disabled?:boolean;className?:string;type?:"button"|"submit"}){return <button type={type} className={"action "+variant+" "+className} onClick={onClick} disabled={disabled}>{children}</button>}
export function PageTitle({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div><div className="heading-actions">{children}</div></div>}
export function SectionTitle({title,description,children}:{title:string;description?:string;children?:ReactNode}){return <div className="section-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{children}</div>}
export function Avatar({student,size=""}:{student:Pick<Student,"name"|"color">;size?:string}){return <span className={"avatar "+size} style={{background:student.color}} title={student.name}>{student.name.split(" ").slice(0,2).map(n=>n[0]).join("")}</span>}
export function AvatarStack({students,limit=4}:{students:Student[];limit?:number}){return <div className="avatar-stack">{students.slice(0,limit).map(s=><Avatar key={s.id} student={s} size="small"/>)}{students.length>limit&&<span className="avatar small more">+{students.length-limit}</span>}</div>}
export function Meter({value,tone=""}:{value:number;tone?:string}){return <Progress aria-label={value+" percent"} value={value} className={"meter "+tone}/>}
export function Score({value}:{value:number|null}){return <span className={"score "+(value===null?"unknown":value>=80?"good":value>=65?"medium":"low")}>{value===null?"—":value+"%"}</span>}
export function EmptyState({title,description,children}:{title:string;description:string;children?:ReactNode}){return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><FileText/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={"teacher-modal "+(wide?"wide":"")}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||"Review the details below."}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function Ring({value,label,small=false}:{value:number;label:string;small?:boolean}){const r=small?43:66,c=2*Math.PI*r;return <div className={"ring-chart "+(small?"small":"")} role="img" aria-label={label+": "+value+" percent"}><svg viewBox={small?"0 0 108 108":"0 0 168 168"}><circle cx={small?54:84} cy={small?54:84} r={r} className="ring-track"/><circle cx={small?54:84} cy={small?54:84} r={r} className="ring-value" strokeDasharray={c} strokeDashoffset={c*(1-value/100)}/></svg><div><strong>{value}<small>%</small></strong><span>{label}</span></div></div>}
export function Insight({children}:{children:ReactNode}){return <div className="insight"><Lightbulb size={19}/><p>{children}</p></div>}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-link" onClick={onClick}>{children}<ArrowRight size={16}/></button>}
export function downloadText(name:string,content:string,type="text/plain"){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
export function emailContent(subject:string,body:string){const max=1800;const truncated=body.length>max?body.slice(0,max)+"\n\n(Report truncated for email — download the full report for every detail.)":body;window.location.href="mailto:?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(truncated)}
export function printContent(title:string,body:string){const frame=document.createElement("iframe");frame.style.cssText="position:fixed;width:0;height:0;border:0;";document.body.appendChild(frame);const doc=frame.contentDocument;if(!doc)return;doc.open();doc.write("<!doctype html><html><head><title></title><style>body{font:15px/1.65 Arial,sans-serif;color:#243e38;padding:32px;max-width:760px;margin:auto}h1{font-size:28px;border-bottom:2px solid #243e38;padding-bottom:14px}pre{font:15px/1.65 Arial,sans-serif;white-space:pre-wrap}footer{font-size:11px;color:#65736e;margin-top:32px}@media print{body{padding:0}}</style></head><body><h1></h1><pre></pre><footer>A Teacher’s Best Friend · Teacher-reviewed instructional materials</footer></body></html>");doc.close();doc.title=title;doc.querySelector("h1")!.textContent=title;doc.querySelector("pre")!.textContent=body;frame.contentWindow?.focus();setTimeout(()=>{frame.contentWindow?.print();setTimeout(()=>frame.remove(),1000)},200)}
