export type Subject = "Math" | "ELA" | "Mixed";
export type Standard = {
  code: string;
  title: string;
  subject: Subject;
  grade: number;
  domain: string;
  cluster: string;
  summary: string;
  skills: string[];
  prerequisites: string[];
  next: string[];
  vocabulary: string[];
  misconception: string;
  example: string;
  dok: number;
  source: string;
  framework: string;
  wording?: string;
  officialCode?: string;
};
export type Evidence = {
  id: string;
  standard: string;
  score: number;
  date: string;
  source: string;
  assessmentId?: string;
};
export type Student = {
  id: string;
  classId: string;
  name: string;
  color: string;
  evidence: Evidence[];
  notes: string;
};
export type Question = {
  id: string;
  number: number;
  text: string;
  passage: string;
  answer: string;
  standard: string;
  secondary: string;
  skill: string;
  dok: number;
  costas?: 1 | 2 | 3;
  alignment: number;
  improvement?: string;
  confidence: number;
  level: "On grade" | "Below grade" | "Above grade" | "Unrelated";
  reasoning: string;
  verified: boolean;
  excluded: boolean;
};
export type StudentResponse = {
  id: string;
  studentId: string;
  questionId: string;
  answer: string;
  correct: boolean;
  match?: number;
  misconception: string;
  confidence: number;
  verified: boolean;
};
export type Assessment = {
  id: string;
  classId: string;
  title: string;
  subject: Subject;
  grade: number;
  framework: string;
  createdAt: string;
  status: "Ready" | "Needs review" | "Draft";
  questions: Question[];
  responses: StudentResponse[];
  uploadIds: string[];
  source: "sample" | "manual" | "ai";
  passage?: string;
  targetStandards: string[];
  answerKeyUploadIds?: string[];
  assignmentUploadIds?: string[];
  studentUploadIds?: Record<string, string[]>;
  answerKeyVerified?: boolean;
};
export type Classroom = {
  id: string;
  name: string;
  grade: number;
  framework: string;
  demo: boolean;
};
export type Lesson = {
  id: string;
  classId: string;
  standard: string;
  title: string;
  duration: number;
  modality: string;
  notes: string;
  date: string;
  completed: boolean;
  studentIds: string[];
  origin: "template" | "ai";
  framework?: string;
  grade?: number;
  assessmentId?: string;
  custom?: {
    objective: string;
    materials: string[];
    phases: { time: string; name: string; text: string }[];
    practice: { q: string; a: string }[];
    exit: { q: string; a: string }[];
  };
};
export type Resource = {
  id: string;
  title: string;
  category: string;
  standard: string;
  content: string;
  uploadId?: string;
  pages?: string;
  classId?: string;
};
export type Group = {
  id: string;
  classId: string;
  name: string;
  standard: string;
  studentIds: string[];
};
export type Workspace = {
  classes: Classroom[];
  activeClassId: string;
  students: Student[];
  assessments: Assessment[];
  lessons: Lesson[];
  resources: Resource[];
  customStandards: Standard[];
  groups: Group[];
  settings: { teacherName: string; school: string; reduceMotion: boolean };
};
export type Priority = {
  standard: Standard;
  students: Student[];
  mastery: number;
  score: number;
  tier: string;
};
